### ISSUE TITLE
最新版 hii min 报错

### ISSUE THREAD

**Issue by huaziHear** [zdying/hiipack#8]
hii min 报错  
hii start运行正常

报错信息如下： 

```
[info] client - clean folder [ prd, ver ] ...
[info] Compiler - compiling [ lib.js ] ...
[info] Compiler - compile finished ( 2933ms )
[info] Compiler - compiling [ orderDetail/app.js ] ...
[info] Compiler - compile finished ( 486ms )
compile result:
Hash: 861ec26824f86f50dc52b6f758527704
Version: webpack 1.13.2
Time: 486ms

ERROR in ./src/orderDetail/app.js
Module build failed: Error: Cannot find module 'babylon' (While processing preset:       "/Users/huazihear/workspace/hotdog/touch_hotdog_react/node_modules/.npminstall/babel-preset-es2015/6.16.0/babel-preset-es2015/lib/index.js")
at Function.Module._resolveFilename (module.js:325:15)
at Function.Module._load (module.js:276:25)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/Users/huazihear/workspace/hotdog/touch_hotdog_react/node_modules/.npminstall/babel-traverse/6.16.0/babel-traverse/lib/path/replacement.js:28:16)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
```

**Comment by huaziHear** [comment]
删除node_modules重新install一把 错误消失...
